# ${project.name} v${project.version}
# @author     ucchy
# @license    LGPLv3
# @copyright  Copyright ucchy 2014

# メッセージの言語
lang: ja

# 1人あたりのItemFrameの設置数上限です。-1で無限大に設定することができます。
itemFrameLimit: 50

# 壁のみが壊されていて、ブロックアップデートが発生したときの、対応モード
# REGEN_STONE -> 石で壁を再生します。ロック情報は維持します。
# EXTINCTION -> 壁を再生せず、額縁および額縁の中身を消去し、ドロップもしないようにします。ロック情報は削除されます。
# ITEM_DROP -> 壁を再生せず、額縁および額縁の中身はアイテムとしてドロップします。ロック情報は削除されます。
wallMode: REGEN_STONE

# 額縁を設置した時に、自動的にロックがかかるかどうかを設定することができます。
autoLock: true
