# ${project.name} v${project.version}
# @author     ucchy
# @license    LGPLv3
# @copyright  Copyright ucchy 2014

# メッセージの言語
lang: ja

# 1人あたりのItemFrameの設置数上限です。-1で無限大に設定することができます。
# パーミッション "gakubuchilock.entity.infinite-place" を持っている人や、OPは、
# この制限を受けずに無制限に設置可能です。
# また、PermissionsExのグループやユーザーのoptionsに、
#   itemFrameLimit: 10
# のように指定すると、そのグループやユーザーのみ、設置数上限を10に変更することができます。
itemFrameLimit: 50

# 壁のみが壊されていて、ブロックアップデートが発生したときの、対応モード
# REGEN_STONE -> 石で壁を再生します。ロック情報は維持します。
# REGEN_STONE_NO_DROP -> 石で壁を再生します。破壊された壁はアイテムをドロップしません。ロック情報は維持します。
# INVINCIBLE -> ロックされた額縁が貼ってある壁は、どんなことをしても壊れなくなります。ロック情報は維持します。
# EXTINCTION -> 壁を再生せず、額縁および額縁の中身を消去し、ドロップもしないようにします。ロック情報は削除されます。
# ITEM_DROP -> 壁を再生せず、額縁および額縁の中身はアイテムとしてドロップします。ロック情報は削除されます。
wallMode: REGEN_STONE_NO_DROP

# 額縁を設置した時に、自動的にロックがかかるかどうかを設定することができます。
autoLock: true

# サーバー起動時に、ロックデータを調査して、既に額縁が無い場合はロックデータをクリーンアップします。
# 正の整数を指定した場合は、サーバー起動から指定時間（分）後に、クリーンアップ処理が実行されます。
# -1 が指定された場合は、クリーンアップ処理を実行しません。
cleanupTaskDelay: -1

# クリーンアップが実行されたときに、削除されたロック情報をコンソールログに表示します。
cleanupTaskLog: true
