# ${project.name} v${project.version}
# @author     ucchy
# @license    LGPLv3
# @copyright  Copyright ucchy 2014

# 1人あたりのItemFrameの設置数上限です。-1で無限大に設定することができます。
itemFrameLimit: -1

# 1人あたりのPaintingの設置数上限です。-1で無限大に設定することができます。
paintingLimit: -1

