name: ${project.name}
version: ${project.version}
main: org.bitbucket.ucchy.glr.GakubuchiLockReloaded
description: ItemFrame lock plugin
author: ucchy
softdepend: [Multiverse-Core,MultiWorld,PermissionsEx]

commands:
  gakubuchilock:
    description: Commands of GakubuchiLock
    aliases: [gl]
    usage: |
           /<command> info - View detail of lock.
           /<command> limits - View information of lock limit.
           /<command> private - Lock item frame.
           /<command> remove - Unlock item frame.
           /<command> persist [lock|unlock|info|off] - Lock/Unlock item frame repeatedly.
           /<command> cleanup (WorldName) - Cleaup all lock datas of the specified world.
           /<command> reload - Reload all of data.
    permission: gakubuchilock.command
    permission-message: 'You don''t have a permission "<permission>".'

  ginfo:
    description: View detail of lock.
    usage: |
           /<command> - View detail of lock.
    permission: gakubuchilock.command.info
    permission-message: 'You don''t have a permission "<permission>".'

  glimits:
    description: View information of lock limit.
    usage: |
           /<command> - View information of lock limit.
    permission: gakubuchilock.command.limits
    permission-message: 'You don''t have a permission "<permission>".'

  gprivate:
    description: Lock item frame.
    usage: |
           /<command> - Lock item frame.
    permission: gakubuchilock.command.private
    permission-message: 'You don''t have a permission "<permission>".'

  gremove:
    description: Unlock item frame.
    usage: |
           /<command> - Unlock item frame.
    permission: gakubuchilock.command.remove
    permission-message: 'You don''t have a permission "<permission>".'

  gpersist:
    description: Lock/Unlock item frame repeatedly.
    usage: |
           /<command> [lock|unlock|info|off] - Lock/Unlock item frame repeatedly.
    permission: gakubuchilock.command.persist
    permission-message: 'You don''t have a permission "<permission>".'

permissions:
  gakubuchilock.command:
    description: Permission of command.
    default: true
  gakubuchilock.command.info:
    description: Permission of info command.
    default: true
  gakubuchilock.command.limits:
    description: Permission of limits command.
    default: true
  gakubuchilock.command.private:
    description: Permission of private command.
    default: true
  gakubuchilock.command.remove:
    description: Permission of remove command.
    default: true
  gakubuchilock.command.persist:
    description: Permission of persist command.
    default: true
  gakubuchilock.command.cleanup:
    description: Permission of cleanup command.
    default: op
  gakubuchilock.command.reload:
    description: Permission of reload command.
    default: op
  'gakubuchilock.command.*':
    description: Permissions of all commands.
    children:
      gakubuchilock.command: true
      gakubuchilock.command.info: true
      gakubuchilock.command.limits: true
      gakubuchilock.command.private: true
      gakubuchilock.command.remove: true
      gakubuchilock.command.persist: true
      gakubuchilock.command.cleanup: true
      gakubuchilock.command.reload: true

  gakubuchilock.entity.place:
    description: Permission to place new ItemFrame.
    default: true
  gakubuchilock.entity.break:
    description: Permission to remove none-locked ItemFrame.
    default: true
  gakubuchilock.entity.interact:
    description: Permission to interact none-locked ItemFrame.
    default: true
  gakubuchilock.entity.admin:
    description: Permission to access none-owner locked ItemFrame.
    default: op
  gakubuchilock.entity.infinite-place:
    description: Permission to place ItemFrame infinite, regardless place limits.
    default: op
  'gakubuchilock.entity.*':
    description: Permissions of all entity access.
    children:
      gakubuchilock.entity.place: true
      gakubuchilock.entity.break: true
      gakubuchilock.entity.interact: true
      gakubuchilock.entity.admin: true
      gakubuchilock.entity.infinite-place: true

  'gakubuchilock.*':
    description: All of permissions.
    children:
      'gakubuchilock.command.*': true
      'gakubuchilock.entity.*': true
